import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "**/dist/**",
      "**/.next/**",
      "**/out/**",
      "**/.turbo/**",
      "**/coverage/**",
      "packages/contracts/lib/**",
      "packages/contracts/out/**",
      "packages/contracts/cache/**",
      "packages/contracts/broadcast/**",
      // Generated by Next; its triple-slash references are not ours to restyle.
      "apps/*/next-env.d.ts",
      "apps/*/.next/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-non-null-assertion": "error",
      // Bridge code deals with bigint amounts; forbid implicit number coercion.
      "@typescript-eslint/restrict-plus-operands": "error",
      "no-console": ["warn", { allow: ["warn", "error"] }],
      eqeqeq: ["error", "always"],
    },
  },
  {
    // node:test's describe/it return promises that the runner owns. Awaiting
    // them is incorrect, so the floating-promise rule does not apply here.
    files: ["**/*.test.ts", "packages/testing/src/**/*.ts"],
    rules: {
      "@typescript-eslint/no-floating-promises": "off",
    },
  },
  {
    files: ["**/*.config.js", "**/*.config.mjs", "eslint.config.js", "prettier.config.js"],
    ...tseslint.configs.disableTypeChecked,
  },
  {
    // Operational scripts run standalone under node and are in no package's
    // tsconfig, so type-aware rules cannot apply. They are CLIs, so writing to
    // stdout is their job rather than a stray debug statement.
    files: ["scripts/**/*.mjs"],
    languageOptions: {
      globals: { console: "readonly", process: "readonly", setTimeout: "readonly" },
    },
    rules: {
      // These are CLIs: writing to stdout is their job.
      "no-console": "off",
      // They read JSON from disk, which is `any` by construction. The values
      // are validated where it matters — deployment artifacts go through
      // parseDeploymentArtifact before anything trusts them — so blanket
      // unsafe-value rules here only produce noise.
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },
  prettier,
);
